project:
  type: website
  output-dir: docs



website:
  site-url: https://vagishhemmige.github.io/Cryptococcus-donor-screening-CEA/
  repo-url: https://github.com/VagishHemmige/Cryptococcus-donor-screening-CEA
  repo-actions: [edit, issue]
  title: "Cryptococcus donor screening cost effectiveness analysis"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: quarto/base_case.html
        text: Base case analysis
      - href: quarto/additional_trees.html
        text: Additional tree analyses
      - href: quarto/tornado.html
        text: One-way sensitivity analysis (tornado plot)
      - href: quarto/psa.html
        text: Probabilistic sensitivity analyses
      - href: quarto/about.html
        text: About
    right:
      - icon: github
        href: https://github.com/VagishHemmige/Cryptococcus-donor-screening-CEA
        aria-label: GitHub repository

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
