project:
  type: website
  output-dir: docs

website:
  title: "Cryptococcus donor screening cost effectiveness analysis"
  navbar:
    left:
      - href: /index.qmd
        text: Home
      - href: /quarto/base_case.qmd
        text: Base case analysis
      - href: /quarto/additional_trees.qmd
        text: Additional tree analyses
      - href: /quarto/tornado.qmd
        text: One-way sensitivity analysis (tornado plot)
      - href: /quarto/psa.qmd
        text: Probabilistic sensitivity analyses
      - href: /quarto/about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
