project:
  type: website
  output-dir: docs

website:
  title: "Cryptococcus donor screening cost effectiveness analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis/model.qmd
        text: Model
      - href: analysis/results.qmd
        text: Results
      - href: analysis/sensitivity.qmd
        text: Sensitivity
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
